<script type="text/javascript" src="/svnapproval/js/jquery.js"></script>
<script type="text/javascript" src="/svnapproval/js/jquery-ui.js"></script>
<script type="text/javascript" src="/svnapproval/js/jquery.bgiframe-2.1.1.js"></script>
  
  
<script type="text/javascript" src="/svnapproval/js/ui/jquery.ui.core.js"></script>
<script type="text/javascript" src="/svnapproval/js/ui/jquery.ui.widget.js"></script>

<script type="text/javascript" src="/svnapproval/js/ui/jquery.ui.button.js"></script>
<script type="text/javascript" src="/svnapproval/js/ui/jquery.ui.position.js"></script>
<script type="text/javascript" src="/svnapproval/js/ui/jquery.ui.autocomplete.js"></script>
  
<link rel="stylesheet" href="/svnapproval/css/jquery-ui-1.8.4.custom.css" type="text/css" />
<link rel="stylesheet" href="/svnapproval/css/jquery.ui.button.css" type="text/css" />



<style type="text/css">
		body { font-size: 62.5%; }
/*		label, input { display:block; } */ 
		input.text { margin-bottom:12px; width:95%; font-size: 14px  }
		fieldset { padding:0; border:0; margin-top:25px; }
		h1 { font-size: 1.2em; margin: .6em 0; }
		div#users-contain { width: 350px; margin: 20px 0; }
		div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
		div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
		.ui-dialog .ui-state-error { padding: .3em; }
		.validateTips { border: 1px solid transparent; padding: 0.3em; }
		
		
		.ui-dialog { position: absolute; padding: .2em; width: 300px; overflow: hidden; }
		.ui-dialog .ui-dialog-titlebar { padding: .5em 1em .3em; position: relative;  }
		.ui-dialog .ui-dialog-title { float: left; margin: .1em 16px .2em 0; } 
		.ui-dialog .ui-dialog-titlebar-close { position: absolute; right: .3em; top: 50%; width: 19px; margin: -10px 0 0 0; padding: 1px; height: 18px; }
		.ui-dialog .ui-dialog-titlebar-close span { display: block; margin: 1px; }
		.ui-dialog .ui-dialog-titlebar-close:hover, .ui-dialog .ui-dialog-titlebar-close:focus { padding: 0; }
		.ui-dialog .ui-dialog-content { position: relative; border: 0; padding: .5em 1em; background: none; overflow: auto; zoom: 1; }
		.ui-dialog .ui-dialog-buttonpane { text-align: left; border-width: 1px 0 0 0; background-image: none; margin: .5em 0 0 0; padding: .3em 1em .5em .4em; }
		.ui-dialog .ui-dialog-buttonpane .ui-dialog-buttonset { float: right; }
		.ui-dialog .ui-dialog-buttonpane button { margin: .5em .4em .5em 0; cursor: pointer; }
		.ui-dialog .ui-resizable-se { width: 14px; height: 14px; right: 3px; bottom: 3px; }
		.ui-draggable .ui-dialog-titlebar { cursor: move; }
				
		
</style>

</head>



<div id="content"> 
	 <? echo $this->layout()->content; ?>
</div>




</html>

