<!DOCTYPE html>
<html>
  <head>

<script type="text/javascript" src="/svnapproval/js/jquery.js"></script>
<script type="text/javascript" src="/svnapproval/js/jquery-ui.js"></script>
<script type="text/javascript" src="/svnapproval/js/jquery.bgiframe-2.1.1.js"></script>
  
  
<script type="text/javascript" src="/svnapproval/js/ui/jquery.ui.core.js"></script>
<script type="text/javascript" src="/svnapproval/js/ui/jquery.ui.widget.js"></script>

<script type="text/javascript" src="/svnapproval/js/ui/jquery.ui.button.js"></script>
<script type="text/javascript" src="/svnapproval/js/ui/jquery.ui.position.js"></script>
<script type="text/javascript" src="/svnapproval/js/ui/jquery.ui.autocomplete.js"></script>
  
<link rel="stylesheet" href="/svnapproval/css/jquery-ui-1.8.4.custom.css" type="text/css" />
<link rel="stylesheet" href="/svnapproval/css/jquery.ui.button.css" type="text/css" />




    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" content="chrome=1">
        <title>bsdperimeter/pfsense-packages - GitHub</title>
    <link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="GitHub" />
    <link rel="fluid-icon" href="https://github.com/fluidicon.png" title="GitHub" />

    
    

    <meta content="authenticity_token" name="csrf-param" />
<meta content="y11vV32XkA/emTCi9W7dwJq/5q1fQ6VM4+dk36/4Tk0=" name="csrf-token" />

    <link href="/svnapproval/css/svnapproval.css" media="screen" rel="stylesheet" type="text/css" />
    

    
  <link href="https://github.com/bsdperimeter/pfsense-packages/commits/master.atom" rel="alternate" title="Recent Commits to pfsense-packages:master" type="application/atom+xml" />

  </head>


  <body class="logged_in  windows vis-public env-production ">
    


    

      <div id="header" class="true clearfix">
        <div class="container clearfix">
          <a class="site-logo" href="https://github.com/">

            <img alt="GitHub" class="github-logo-4x" height="30" src="/images/modules/header/logov7@4x.png?1323882778" />
            <img alt="GitHub" class="github-logo-4x-hover" height="30" src="/images/modules/header/logov7@4x-hover.png?1324325424" />
          </a>

              
    <div class="topsearch ">
<form action="/search" id="top_search_form" method="get">        <a href="/search" class="advanced-search tooltipped downwards" title="Advanced Search">Advanced Search</a>
        <div class="search placeholder-field js-placeholder-field">
          <label class="placeholder" for="global-search-field">Search…</label>

          <input type="text" class="search my_repos_autocompleter" id="global-search-field" name="q" results="5" /> <input type="submit" value="Search" class="button" />
        </div>
        <input type="hidden" name="type" value="Everything" />
        <input type="hidden" name="repo" value="" />
        <input type="hidden" name="langOverride" value="" />
        <input type="hidden" name="start_value" value="1" />
</form>      <ul class="top-nav">
          <li class="explore"><a href="https://github.com/explore">Explore</a></li>

          <li><a href="https://gist.github.com">Gist</a></li>
          <li><a href="/blog">Blog</a></li>
        <li><a href="http://help.github.com">Help</a></li>
      </ul>
    </div>


            


  <div id="userbox">

    <div id="user">
      <a href="https://github.com/jorgelustosa" class="name">jorgelustosa</a>
    </div>
    <ul id="user-links">
      <li>
        <a href="/inbox/notifications" id="notifications" class="tooltipped downwards" title="Notifications">
          <span class="icon">Notifications</span>

        </a>
      </li>
      <li><a href="/account" id="settings" class="tooltipped downwards" title="Account Settings"><span class="icon">Account Settings</span></a></li>
      <li><a href="/logout" id="logout" class="tooltipped downwards" title="Log Out"><span class="icon">Log Out</span></a></li>
    </ul>
  </div>



          
        </div>
      </div>



   <div class="site">
      <div class="container">
        <div class="pagehead repohead instapaper_ignore readability-menu">


        <div class="title-actions-bar">
          <h1>

            <a href="/bsdperimeter">bsdperimeter</a> /
            <strong><a href="/bsdperimeter/pfsense-packages" class="js-current-repository">pfsense-packages</a></strong>
          </h1>
          



              <ul class="pagehead-actions">


          <li class="js-toggler-container watch-button-container on">
            <a href="/bsdperimeter/pfsense-packages/toggle_watch" class="minibutton btn-watch watch-button js-toggler-target" data-method="post" data-remote="true" rel="nofollow"><span><span class="icon"></span>Watch</span></a>

            <a href="/bsdperimeter/pfsense-packages/toggle_watch" class="minibutton btn-watch unwatch-button js-toggler-target" data-method="post" data-remote="true" rel="nofollow"><span><span class="icon"></span>Unwatch</span></a>
          </li>

              <li><a href="/jorgelustosa/pfsense-packages" class="minibutton btn-fork "><span><span class="icon"></span>Your Fork</span></a></li>



      <li class="repostats">
        <ul class="repo-stats">
          <li class="watchers watching">

            <a href="/bsdperimeter/pfsense-packages/watchers" title="Watchers — You're Watching" class="tooltipped downwards">
              32
            </a>
          </li>
          <li class="forks">
            <a href="/bsdperimeter/pfsense-packages/network" title="Forks - You have a fork" class="tooltipped downwards">
              13
            </a>
          </li>
        </ul>

      </li>
    </ul>

        </div>




  <ul class="tabs">
    <li><a href="/bsdperimeter/pfsense-packages" class="selected" highlight="repo_sourcerepo_downloadsrepo_commitsrepo_tagsrepo_branches">Code</a></li>
    <li><a href="/bsdperimeter/pfsense-packages/network" highlight="repo_networkrepo_fork_queue">Network</a>
    <li><a href="/bsdperimeter/pfsense-packages/pulls" highlight="repo_pulls">Pull Requests <span class='counter'>2</span></a></li>

      <li><a href="/bsdperimeter/pfsense-packages/issues" highlight="repo_issues">Issues <span class='counter'>2</span></a></li>


    <li><a href="/bsdperimeter/pfsense-packages/graphs" highlight="repo_graphsrepo_contributors">Stats &amp; Graphs</a></li>

  </ul>

      <div id="repo_details" class="metabox clearfix
        not-editable">

      <div id="repo_details_loader" class="metabox-loader" style="display:none">Sending Request&hellip;</div>

      <div class="repo-desc-homepage">
        
<div style="display:none">
  <div class="repository-lang-stats">
    <div class="repository-lang-stats-graph">
    <span data-lang="PHP" style="width:90%"></span><span data-lang="Perl" style="width:5%"></span><span data-lang="JavaScript" style="width:2%"></span><span data-lang="C" style="width:2%"></span><span data-lang="Other" style="width:1%"></span>
    </div>
    <ol class="list-tip">

      <li>
        <span data-lang="PHP" class="color-block"></span>
        <span class="lang">PHP</span>
        <span class="percent">90%</span>
      </li>
      <li>
        <span data-lang="Perl" class="color-block"></span>
        <span class="lang">Perl</span>

        <span class="percent">5%</span>
      </li>
      <li>
        <span data-lang="JavaScript" class="color-block"></span>
        <span class="lang">JavaScript</span>
        <span class="percent">2%</span>
      </li>

      <li>
        <span data-lang="C" class="color-block"></span>
        <span class="lang">C</span>
        <span class="percent">2%</span>
      </li>
      <li>
        <span data-lang="Other" class="color-block"></span>
        <span class="lang">Other</span>

        <span class="percent">1%</span>
      </li>
    </ol>
  </div>
</div>

<div id="repository_description" class="repository-description">
    <p>pfSense packages repository
      <span id="read_more" style="display:none">&mdash; <a href="#readme">Read more</a></span>

    </p>
</div>


<div class="repository-homepage" id="repository_homepage">
  <p><a href="http://www.pfsense.org" rel="nofollow">http://www.pfsense.org</a></p>
</div>


      </div>

      <div class="edit-repo-desc-homepage" style="display:none">

<form action="/bsdperimeter/pfsense-packages/admin/update_meta" id="js-update-repo-meta-form" method="post"><div style="margin:0;padding:0;display:inline"><input name="_method" type="hidden" value="put" /><input name="authenticity_token" type="hidden" value="y11vV32XkA/emTCi9W7dwJq/5q1fQ6VM4+dk36/4Tk0=" /></div>          <p class="error" style="display:none">Sorry, but there was a problem saving your changes.</p>

          <div class="placeholder-field description-field-wrap js-placeholder-field">
            <label class="placeholder" for="repository-description-field" data-placeholder-mode="sticky">Add a description to this repository</label>
            <input type="text" id="repository-description-field" class="description-field" name="repo_description" value="pfSense packages repository" />
          </div>

          <div class="placeholder-field homepage-field-wrap js-placeholder-field">
            <label class="placeholder" for="repository-homepage-field" data-placeholder-mode="sticky">Add a website to this repository</label>

            <input type="text" id="repository-homepage-field" class="homepage-field" name="repo_homepage" value="http://www.pfsense.org" />
          </div>

          <button type="submit" class="classy save-button"><span>Save Changes</span></button>
          <p class="cancel"><a href="#" class="danger">Cancel</a></p>
</form>      </div>

      
<div class="url-box">
  <ul class="native-clones">

      <li><a href="/bsdperimeter/pfsense-packages/zipball/master" class="minibutton btn-download " rel="nofollow" title="Download this repository as a zip file"><span><span class="icon"></span>ZIP</span></a>
  </ul>

  <ul class="clone-urls">
      <li class="http_clone_url"><a href="https://github.com/bsdperimeter/pfsense-packages.git" data-permissions="Read-Only">HTTP</a></li>
        <li class="public_clone_url"><a href="git://github.com/bsdperimeter/pfsense-packages.git" data-permissions="Read-Only">Git Read-Only</a></li>
  </ul>
  <input type="text" spellcheck="false" class="url-field" />

        <span style="display:none" id="clippy_3871" class="clippy-text"></span>
      <span id="clippy_tooltip_clippy_3871" class="clippy-tooltip tooltipped" title="copy to clipboard">
      <object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000"
              width="14"
              height="14"
              class="clippy"
              id="clippy" >
      <param name="movie" value="/flash/clippy.swf?1284681402?v5"/>
      <param name="allowScriptAccess" value="always" />
      <param name="quality" value="high" />
      <param name="scale" value="noscale" />
      <param NAME="FlashVars" value="id=clippy_3871&amp;copied=copied!&amp;copyto=copy to clipboard">
      <param name="bgcolor" value="#FFFFFF">

      <param name="wmode" value="opaque">
      <embed src="/flash/clippy.swf?1284681402?v5"
             width="14"
             height="14"
             name="clippy"
             quality="high"
             allowScriptAccess="always"
             type="application/x-shockwave-flash"
             pluginspage="http://www.macromedia.com/go/getflashplayer"
             FlashVars="id=clippy_3871&amp;copied=copied!&amp;copyto=copy to clipboard"
             bgcolor="#FFFFFF"
             wmode="opaque"
      />
      </object>
      </span>

  <p class="url-description"><strong>Read+Write</strong> access</p>
</div>

    </div>

<div class="frame frame-center tree-finder" style="display:none"
      data-tree-list-url="/bsdperimeter/pfsense-packages/tree-list/77843d5bf49396612310007b236a74b252f3fbba"
      data-blob-url-prefix="/bsdperimeter/pfsense-packages/blob/77843d5bf49396612310007b236a74b252f3fbba"
    >

  <div class="breadcrumb">
    <b><a href="/bsdperimeter/pfsense-packages">pfsense-packages</a></b> /
    <input class="tree-finder-input js-navigation-enable" type="text" name="query" autocomplete="off" spellcheck="false">
  </div>

    <div class="octotip">
      <p>

        <a href="/bsdperimeter/pfsense-packages/dismiss-tree-finder-help" class="dismiss js-dismiss-tree-list-help" title="Hide this notice forever" rel="nofollow">Dismiss</a>
        <strong>Octotip:</strong> You've activated the <em>file finder</em>
        by pressing <span class="kbd">t</span> Start typing to filter the
        file list. Use <span class="kbd badmono">↑</span> and
        <span class="kbd badmono">↓</span> to navigate,
        <span class="kbd">enter</span> to view files.
      </p>

    </div>

  <table class="tree-browser" cellpadding="0" cellspacing="0">
    <tr class="js-header"><th>&nbsp;</th><th>name</th></tr>
    <tr class="js-no-results no-results" style="display: none">
      <th colspan="2">No matching files</th>
    </tr>
    <tbody class="js-results-list js-navigation-container" data-navigation-enable-mouse>

    </tbody>
  </table>
</div>

<div id="jump-to-line" style="display:none">
  <h2>Jump to Line</h2>
  <form>
    <input class="textfield" type="text">
    <div class="full-button">
      <button type="submit" class="classy">

        <span>Go</span>
      </button>
    </div>
  </form>
</div>


<div class="subnav-bar">

  <ul class="actions">
    
      <li class="switcher">

        <div class="context-menu-container js-menu-container">
          <span class="text">Current branch:</span>
          <a href="#"
             class="minibutton bigger switcher context-menu-button js-menu-target js-commitish-button btn-branch repo-tree"
             data-master-branch="master"
             data-ref="master">
            <span><span class="icon"></span>master</span>
          </a>

          <div class="context-pane commitish-context js-menu-content">
            <a href="javascript:;" class="close js-menu-close"></a>

            <div class="context-title">Switch Branches/Tags</div>
            <div class="context-body pane-selector commitish-selector js-filterable-commitishes">
              <div class="filterbar">
                <div class="placeholder-field js-placeholder-field">
                  <label class="placeholder" for="context-commitish-filter-field" data-placeholder-mode="sticky">Filter branches/tags</label>
                  <input type="text" id="context-commitish-filter-field" class="commitish-filter" />
                </div>

                <ul class="tabs">
                  <li><a href="#" data-filter="branches" class="selected">Branches</a></li>
                  <li><a href="#" data-filter="tags">Tags</a></li>
                </ul>
              </div>

                <div class="commitish-item branch-commitish selector-item">
                  <h4>

                      <a href="/bsdperimeter/pfsense-packages/tree/master" data-name="master" rel="nofollow">master</a>
                  </h4>
                </div>


              <div class="no-results" style="display:none">Nothing to show</div>
            </div>
          </div><!-- /.commitish-context-context -->
        </div>

      </li>
  </ul>

  <ul class="subnav">
    <li><a href="/bsdperimeter/pfsense-packages" class="selected" highlight="repo_source">Files</a></li>
    <li><a href="/bsdperimeter/pfsense-packages/commits/master" highlight="repo_commits">Commits</a></li>
    <li><a href="/bsdperimeter/pfsense-packages/branches" class="" highlight="repo_branches" rel="nofollow">Branches <span class="counter">1</span></a></li>

    <li><a href="/bsdperimeter/pfsense-packages/tags" class="blank" highlight="repo_tags">Tags <span class="counter">0</span></a></li>
    <li><a href="/bsdperimeter/pfsense-packages/downloads" class="blank" highlight="repo_downloads">Downloads <span class="counter">0</span></a></li>
  </ul>

</div>

  
  
  


          

        </div><!-- /.repohead -->

        




  
  <p class="last-commit">Latest commit to the <strong>master</strong> branch</p>

<div class="commit commit-tease js-details-container">
  <p class="commit-title ">
      <a href="/bsdperimeter/pfsense-packages/commit/77843d5bf49396612310007b236a74b252f3fbba" class="message">Merge pull request </a><a href="https://github.com/bsdperimeter/pfsense-packages/issues/205" title="updates to dns-server package. (fixes dnscache)" class="issue-link">#205</a><a href="/bsdperimeter/pfsense-packages/commit/77843d5bf49396612310007b236a74b252f3fbba" class="message"> from lfitt/master</a>
      <a href="javascript:;" class="minibutton expander-minibutton js-details-target"><span>…</span></a>
  </p>
    <div class="commit-desc"><pre>updates to dns-server package. (fixes dnscache)</pre></div>

  <div class="commit-meta">
    <a href="/bsdperimeter/pfsense-packages/commit/77843d5bf49396612310007b236a74b252f3fbba" class="sha-block">commit <span class="sha">77843d5bf4</span></a>

    <div class="authorship">
      <img class="gravatar" height="20" src="https://secure.gravatar.com/avatar/a009aab5cbbe27969ee4173888e6f716?s=140&amp;d=%2Fimages%2Fgravatars%2Fgravatar-140.png" width="20" />
      <span class="author-name"><a href="/jim-p">jim-p</a></span>
      authored <time class="js-relative-date" datetime="2012-01-24T05:06:40-08:00" title="2012-01-24 05:06:40">January 24, 2012</time>

    </div>
  </div>
</div>


  <div id="slider">
      <div class="breadcrumb" data-path="/">
        <b><a href="/bsdperimeter/pfsense-packages/tree/77843d5bf49396612310007b236a74b252f3fbba" class="js-rewrite-sha">pfsense-packages</a></b> / 
      </div>

        

  <div class="frames">
    <div class="frame frame-center" data-path="/" data-permalink-url="/bsdperimeter/pfsense-packages/tree/77843d5bf49396612310007b236a74b252f3fbba" data-title="bsdperimeter/pfsense-packages - GitHub" data-type="tree" data-cached-commit-url="/bsdperimeter/pfsense-packages/cache/commits/77843d5bf49396612310007b236a74b252f3fbba?commit_sha=77843d5bf49396612310007b236a74b252f3fbba&amp;path=">
      
      
     <div id="content"> 
	 <? echo $this->layout()->content; ?>
</div>

      
      
    </div>
  </div>
  <br style="clear:both;">


<br style="clear:both;">

<div class="frame frame-loading" style="display:none;" data-tree-list-url="/bsdperimeter/pfsense-packages/tree-list/77843d5bf49396612310007b236a74b252f3fbba" data-blob-url-prefix="/bsdperimeter/pfsense-packages/blob/77843d5bf49396612310007b236a74b252f3fbba">
  <img src="/images/modules/ajax/big_spinner_336699.gif?1315867479" height="32" width="32">

</div>


  </div>


      </div>



      <div class="context-overlay"></div>
    </div>


      <!-- footer -->
   
    

    
    
    
  </body>
</html>



