<script type="text/javascript" src="/svnapproval/js/svn_file.js"></script>

<p class="last-commit">Latest commit to the <strong>master</strong> branch</p>

<div class="commit commit-tease js-details-container" id="last_commit"></div>


  <div id="slider">
      <div class="breadcrumb" data-path="/">
        <b><a style="cursor:pointer" onclick="opendir('<? echo $this->folder ?>')"  class="js-rewrite-sha"><? echo $this->project_name ?></a></b> / 
      </div>

  <div class="frames">
    <div class="frame frame-center" data-path="/" data-permalink-url="/bsdperimeter/pfsense-packages/tree/77843d5bf49396612310007b236a74b252f3fbba" data-title="bsdperimeter/pfsense-packages - GitHub" data-type="tree" data-cached-commit-url="/bsdperimeter/pfsense-packages/cache/commits/77843d5bf49396612310007b236a74b252f3fbba?commit_sha=77843d5bf49396612310007b236a74b252f3fbba&amp;path=">


<div class="bubble tree-browser-wrapper" id="filemanager"></div>

<div id="fileschange">


<div class="breadcrumb" data-path="/" >
        <b><a style="cursor:pointer" class="js-rewrite-sha"> Changed Files </a></b> 
</div>

<div class="bubble tree-browser-wrapper" id="changedfiles"></div>      
 
<div class="bubble">
<div data-repository="1740059" class="comment-form previewable-comment-form previewable-comment-form-attached">
  <div class="tab-content" id="write_bucket_50" style="display: block;">
    <textarea data-suggester-list="comment_body_50_mentions" id="comment_body_50" tabindex="1" name="comment[body]"></textarea>
  </div>
  <div class="new-comments tab-content" id="preview_bucket_50" style="display: none;">
<div class="comment normal-comment" id="openstruct-177421540">
  <div class="body">
    <div class="formatted-content">
</div>
</div>
</div>
</div>
</div>
</div>

<br>
 
 
<!--  Buttons  -->
 
<a data-ref="master" data-master-branch="master" class="minibutton bigger switcher context-menu-button js-menu-target js-commitish-button btn-branch repo-tree" id="add_file">
            <span><span class="icon"></span>add</span>
          </a> 
 
<a data-ref="master" data-master-branch="master" class="minibutton bigger switcher context-menu-button js-menu-target js-commitish-button btn-branch repo-tree"  id="commit_file" >
            <span><span class="icon"></span>commit</span>
          </a> 
 
<a data-ref="master" data-master-branch="master" class="minibutton bigger switcher context-menu-button js-menu-target js-commitish-button btn-branch repo-tree"  id="delete_file" >
            <span><span class="icon"></span>delete</span>
          </a> 


<!--  alerts  -->

<br>
<br>
<br>


</div>

<div id="missing-readme" style="display: none"></div>


 
 
 

 
 
 
 