<script type="text/javascript" src="/svnapproval/js/svn_file.js"></script>
<?

$content = $this->content ;

$status = $this->status ;

//print_r($status) ; 
		
?> 




<table border="0" cellpadding="2" cellspacing="0" width=100%>
<tr>
<td colspan=6></td>

<td >
<select name="folder" id="folder" > 
<option value =""></option>
<option value ="/srv/svnapproval/">svnapproval</option>
<option value ="/srv/intranet/">intranet</option>
</select></td>
</tr>



<tr  width=100%>
<td width=300>Filename
<td width=65>Size
<td align="center" width=44>Open
<td align="center" width=58>Rename
<td align="center" width=57>Delete
<td align="center" width=40>Move
<td align="center" width=44>View
<tr height="2"><td height="2" colspan="3">;
		
<?  

	for ($a=1; $a<count($content)+1;$a++) 
	{
	
		if(isset($status["".$content[$a]["NAME"].""]))
		{ 
		  $status_file = $status["".$content[$a]["NAME"]] ; 
		} else 
		{ 
			$status_file = "" ; 
		} 
	
?> 
<tr  width=100%> 
	<td>
	<input type="checkbox" value="<? echo $content[$a]["NAME"]?>" id="<? echo $content[$a]["NAME"]?>">
	<a href="?folder=<? echo $content[$a]["NAME"] ?>/"><? echo $content[$a]["NAME"]." ".$status_file ?></a>
	</td>
	
	<? if($content[$a]["TYPE"] == "D")  
	{ 
		// verify if file is modified or other stuff  
	?> 
	<td align="center"><a href="?folder=<? echo $content[$a]["NAME"] ?>/">Open</a></td>
	<? 
	}
	else
	{
	?>  
	<td align="center"></td>
	<? 
	} 
	?>   
	
	
	
	<td align="center"><a href="">Rename</a></td>
	<td align="center"><a href="">Delete</a></td>
	<td align="center"><a href="">Move</a></td>
</tr>
<? 
	}
 

?> 	


</table>

<br>
<table> 
<tr>
<td><input type="button" value="add" id="add_file"></td>
</tr>
</table> 

<div id="added_files">
</div>




